---
- name: DEMONSTRATE LOCKING
  hosts: fortimanager
  connection: local
  gather_facts: false
  tasks:
   - name: GET FACTS
     fortimgr_facts:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       adom: "lab"

   - name: GET FORTIGATE FACTS
     fortimgr_facts:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       adom: "lab"
       fortigates: "lab"

   - name: GET FORTIGATE FACTS
     fortimgr_facts:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       adom: "lab"
       fortigates:
         - "lab"
         - "prod"
         - "dmz"

   - name: GET ALL CONFIGS
     fortimgr_facts:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       adom: "lab"
       fortigates: "all"
       config_filter: "all"

   - name: GET SOME CONFIGS
     fortimgr_facts:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       adom: "lab"
       fortigates:
         - name: "lab"
           vdom: "root"
         - name: "prod"
           vdom: "root"
         - name: "dmz"
           vdom: "web"
         - name: "dmz"
           vdom: "dmz"
       config_filter:
         - "routes"
         - "policy"

