---
- name: ENSURE IP POOLS ARE IN DESIRED STATE
  hosts: fortimanager
  connection: local
  gather_facts: false

  tasks:
    - name: ENSURE IP POOLS OVERLOAD EXIST
      fortimgr_ip_pool:
        provider: "{{ fortimanager_provider }}"
        pool_name: "{{ item.name }}"
        type: "overload"
        start_ip: "{{ item.start }}"
        end_ip: "{{ item.end }}"
        comment: "Lab Pool"
      with_items: "{{ pools.overload }}"

    - name: ENSURE IP POOL MAPPINGS EXIST
      fortimgr_ip_pool_map:
        provider: "{{ fortimanager_provider }}"
        fortigate: "{{ item.fg }}"
        pool_name: "{{ item.name }}"
        type: "overload"
        start_ip: "{{ item.start }}"
        end_ip: "{{ item.end }}"
      with_items: "{{ pools.mappings }}"
