---
- name: ENSURE IP POOLS ARE IN DESIRED STATE
  hosts: fortimanager
  connection: local
  gather_facts: false
  tasks:
    - name: CREATE PROVIDER
      set_fact:
        fortimanager_provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"

    - name: ENSURE IP POOLS OVERLOAD EXIST
      fortimgr_ip_pool:
        provider: "{{ fortimanager_provider }}"
        pool_name: "{{ item.name }}"
        type: "overload"
        start_ip: "{{ item.start }}"
        end_ip: "{{ item.end }}"
        comment: "Lab Pool"
      with_items: "{{ pools.overload }}"

    - name: ENSURE IP POOL MAPPINGS EXIST
      fortimgr_ip_pool_map:
        provider: "{{ fortimanager_provider }}"
        fortigate: "{{ item.fg }}"
        vdom: "{{ item.vdom }}"
        pool_name: "{{ item.name }}"
        type: "overload"
        start_ip: "{{ item.start }}"
        end_ip: "{{ item.end }}"
      with_items: "{{ pools.mappings }}"
