---
- name: GET FACTS FROM FORTIMANAGER
  hosts: fortimanager
  connection: local
  gather_facts: false
  tasks:
    - name: CREATE PROVIDER
      set_fact:
        fortimanager_provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"

    - name: ADD ROUTE
      fortimgr_route:
        provider: "{{ fortimanager_provider }}"
        fortigate: "labfg"
        vdom: "root"
        destination: "{{ item.dest }}"
        gateway: "{{ item.gateway }}"
        intfc: "{{ item.interface }}"
      with_items: "{{ routes }}"
