---
- name: DEMONSTRATE REVISIONS
  hosts: fortimanager
  connection: local
  gather_facts: false
  tasks:
    - name: CREATE NEW REVISION
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        created_by: "user"
        description: "ADOM Revision"
        revision_name: "Lab Revision"

    - name: DELETE REVISION
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        revision_name: "Lab Revision"
        state: "absent"

    - name: RESTORE REVISION
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        created_by: "user"
        description: "ADOM Revert"
        revision_name: "Good Revision"
        restore_name: "Rollback"
        state: "restore"
