---
- name: ENSURE FORTIGATE ROUTES ARE IN DESIRED STATE
  hosts: fortimanager
  connection: local
  gather_facts: false

  tasks:
    - name: ENSURE ROUTE EXISTS ON FORTGATE
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab_fg"
        vdom: "lab"
        destination: "10.10.140.0/24"
        gateway: "10.1.100.1"
        intfc: "corp"

    - name: ENSURE ROUTE DOES NOT EXIST ON FORTGATE
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab_fg"
        vdom: "lab"
        destination: "10.10.140.0/24"
        gateway: "10.1.100.1"
        intfc: "corp"
        state: "absent"
