---
- name: ENSURE SERVICE OBJECTS ARE IN DESIRED STATE
  hosts: fortimanager
  connection: local
  gather_facts: false

  tasks:
    - name: ENSURE SERVICE OBJECT TCP EXISTS
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "http_svc"
        protocol: "tcp"
        port_range: "80"
        comment: "Web Services"

    - name: ENSURE SERVICE OBJECT TCP EXISTS
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "web_svc"
        protocol: "tcp"
        port_range:
          - "80"
          - "443"
        comment: "Web Services"

    - name: ENSURE SERVICE OBJECT TCP PORT DOES NOT EXIST
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "web_svc"
        port_range: "80"
        state: "param_absent"

    - name: ENSURE SERVICE OBJECT UDP EXISTS
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "snmp_svc"
        protocol: "udp"
        port_range: "161-162"

    - name: ENSURE SERVICE OBJECT ICMP EXISTS
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "icmp_echo_svc"
        protocol: "icmp"
        icmp_code: 0
        icmp_type: 8

    - name: ENSURE SERVICE OBJECT IP EXISTS
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "ah_svc"
        protocol: "ip"
        protocol_number: 51   
        
    - name: ENSURE SERVICE GROUP EXISTS
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        members:
          - "web_svc"
          - "snmp_svc"

    - name: ENSURE SERVICE GROUP MEMBER DOES NOT EXIST
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        members: "snmp_svc"
        state: "param_absent"

    - name: ENSURE SERVICE GROUP DOES NOT EXIST
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        state: "absent"

    - name: ENSURE SERVICE OBJECT IP DOES NOT EXIST
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "ah_svc"
        state: "absent"
