---
- name: Ensure Service Objects Are in Desired State
  hosts: fortimanager
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure Service Object TCP Exists
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "http_svc"
        protocol: "tcp"
        port_range: "80"
        comment: "Web Services"

    - name: Ensure Service Object TCP Exists
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "web_svc"
        protocol: "tcp"
        port_range:
          - "80"
          - "443"
        comment: "Web Services"

    - name: Ensure Service Object TCP Port Does Not Exist
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "web_svc"
        port_range: "80"
        state: "param_absent"

    - name: Ensure Service Object UDP Exists
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "snmp_svc"
        protocol: "udp"
        port_range: "161-162"

    - name: Ensure Service Object ICMP Exists
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "icmp_echo_svc"
        protocol: "icmp"
        icmp_code: 0
        icmp_type: 8

    - name: Ensure Service Object IP Exists
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "ah_svc"
        protocol: "ip"
        protocol_number: 51   
        
    - name: Ensure Service Group Exists
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        members:
          - "web_svc"
          - "snmp_svc"

    - name: Ensure Service Group Member Does Not Exist
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        members: "snmp_svc"
        state: "param_absent"

    - name: Ensure Service Group Does Not Exist
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name_group: "lab_svcgrp"
        state: "absent"

    - name: Ensure Service Object IP Does Not Exist
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "ah_svc"
        state: "absent"
