---
- name: ENSURE VIP ADDRESSES ARE IN DESIRED STATE
  hosts: fortimanager
  connection: local
  gather_facts: false
  tasks:
    - name: ENSURE VIP STATIC-NAT EXISTS
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "lab_vip_01"
        type: "static-nat"
        external_ip: "10.1.1.1"
        mapped_ip: "100.1.1.1"
        external_intfc: "lab"
        comment: "Lab VIP"

    - name: ENSURE VIP STATIC-NAT EXISTS
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "lab_vip_02"
        type: "static-nat"
        external_ip: "10.1.1.2"
        mapped_ip: "100.1.1.2"
        external_intfc: "lab"
        comment: "Lab VIP"

    - name: ENSURE VIP GROUP EXISTS
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vip_grp_01"
        members:
          - "lab_vip_01"
          - "lab_vip_02"

    - name: ENSURE VIP GROUP MEMBER DOES NOT EXIST
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vip_grp_01"
        members:
          - "lab_vip01"
        state: "param_absent"

    - name: ENSURE VIP MAPPINGS EXIST
      fortimgr_vip_map:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "{{ item.fg }}"
        vdom: "root"
        vip_name: "lab_vip_03"
        type: "static-nat"
        external_ip: "{{ item.ext }}"
        mapped_ip: "{{ item.map }}"
        external_intfc: "lab"
      with_items:
        - fg: "lab1"
          ext:
            - "10.1.1.3"
          map:
            - "10.1.1.3"
        - fg: "lab2"
          ext:
            - "10.1.2.3"
          map:
            - "10.1.2.3"

    - name: ENSURE VIP MAPPING DOES NOT EXIST
      fortimgr_vip_map:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        vip_name: "lab_vip_03"
        state: "absent"

    - name: ENSURE VIP GROUP DOES NOT EXIST
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "addr_grp_01"
        state: "absent"

    - name: ENSURE VIP DOES NOT EXIST
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip_lab_01"
        state: "absent"
