---

- name: CREATE FORTIMANAGER ADDRESS FOR UNIT TESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  
  tasks:
    - name: CREATE ADDRESS OBJECT - CHANGE
      fortimgr_address:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        address_name: "route_unittest"
        address_type: "ipmask"
        subnet:
          - "10.2.1.1"
          - "255.255.255.255"
        allow_routing: "enable"

- name: FORTIMANAGER ROUTE UNITTESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  
  tasks:
    - name: CREATE ROUTE LIST NOTATION - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"

    - name: CREATE ROUTE AGAIN LIST NOTATION - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"

    - name: CREATE ROUTE CIDR NOTATION - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination: "10.20.10.0/24"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      register: config_results

    - name: CREATE ROUTE CIDR NOTATION AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "10.20.10.0/24"
        gateway: "10.1.1.1"
        intfc: "port1"

    - name: CREATE ROUTE HOST NOTATION - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination: "10.20.16.16"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"

    - name: CREATE ROUTE HOST NOTATION AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "10.20.16.16"
        gateway: "10.1.1.1"
        intfc: "port1"

    - name: CREATE ROUTE NET AND MASK NOTATION - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_network: "10.30.10.0"
        destination_netmask: "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"

    - name: CREATE ROUTE NET AND MASK NOTATION AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination_network: "10.30.10.0"
        destination_netmask: "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"

    - name: CREATE ROUTE ADDRESS OBJECT - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      ignore_errors: true

    - name: CREATE ROUTE ADDRESS OBJECT AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
      ignore_errors: true

    - name: DELETE ROUTE ADDRESS OBJECT - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
        state: "absent"

    - name: DELETE ROUTE ADDRESS OBJECT AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
        state: "absent"

    - name: ADD ROUTE TO DIFFERENT GATEWAY - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.2"
        intfc: "port1"

    - name: MODIFY ROUTE'S INTERFACE USING SEQUENCE NUMBER - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        sequence_number: "{{ config_results.config.params[0].data.get('seq-num') }}"
        intfc: "port2"

    - name: ADD ROUTE THROUGH DIFFERENT INTERFACE - FAIL
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.2"
        intfc: "port2"
      ignore_errors: True

    - name: ADD ROUTE MISSING GATEWAY - FAIL
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        intfc: "port2"
      ignore_errors: True

    - name: ADD ROUTE MISSING DESTINATION - FAIL
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        gateway: "10.1.1.1"
        intfc: "port2"
      ignore_errors: True

    - name: ADD ROUTE DESTINATION ADDRESS AND OBJECT - FAIL
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        destination_object: "route_unittest"
        intfc: "port2"
      ignore_errors: True

    - name: DELETE ROUTE - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "{{ item }}"
        intfc: "port1"
        state: "absent"
      with_items:
        - "10.1.1.1"
        - "10.1.1.2"

    - name: DELETE ROUTE AGAIN - NO CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        state: "absent"

    - name: DELETE ROUTE - CHANGE
      fortimgr_route:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "{{ item }}"
        gateway: "10.1.1.1"
        intfc: "port1"
        state: "absent"
      with_items:
        - "10.20.10.0/24"
        - "10.30.10.0/24"
        - "10.20.16.16"
      tags: cleanup

- name: DELETE FORTIMANAGER ADDRESS FOR UNIT TESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  tags: cleanup
  
  tasks:
    - name: DELETE ADDRESS OBJECT - CHANGE
      fortimgr_address:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        address_name: "route_unittest"
        address_type: "ipmask"
        subnet:
          - "10.2.1.1"
          - "255.255.255.255"
        state: "absent"