---
- name: CREATE FORTIMANAGER SERVICES FOR UNIT TESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  
  tasks:
    - name: CREATE SERVICE - CHANGE
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "{{ item.name }}"
        protocol: "TCP"
        port_range:
          - "{{ item.port }}"
      with_items:
        - name: "svc1"
          port: 1
        - name: "svc2"
          port: 2
        - name: "svc3"
          port: 3
        - name: "svc4"
          port: 4


- name: FORTIMANAGER SERVICE GROUP UNITTESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  
  tasks:
    - name: CREATE SERVICE GROUP - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"
        color: 18

    - name: CREATE SERVICE GROUP AGAIN - NO CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"
        color: "18"

    - name: SET PROVIDER - NO CHANGE
      set_fact:
        provider:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          adom: "lab"
          service_group_name: "svcgrp1"
          members: "svc1"
          comment: "service group unit test"
          color: "18"

    - name: CREATE SERVICE GROUP WITH PROVIDER - NO CHANGE
      fortimgr_service_group:
        provider: "{{ provider }}"

    - name: CREATE SERVICE GROUP OVERRIDE PROVIDER - CHANGE
      fortimgr_service_group:
        provider: "{{ provider }}"
        service_group_name: "provider_svcgrp1"
        members:
          - "svc3"
          - "svc4"
        comment: "service group unit test"
        color: 14

    - name: MODIFY SERVICE GROUP ADD MEMBER WITH EXISTING MEMBERS - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
          - "svc3"
        comment: "service group unit test"

    - name: MODIFY SERVICE GROUP ADD MEMBER WITHOUT EXISTING MEMBERS - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc4"
        comment: "service group unit test"

    - name: MODIFY SERVICE GROUP REMOVE MEMBER - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        state: "param_absent"
        comment: "service group unit test"

    - name: MODIFY SERVICE GROUP REMOVE MEMBER AGAIN - NO CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        state: "param_absent"
        comment: "service group unit test"

    - name: CREATE SERVICE GROUP - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp2"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"

    - name: DELETE SERVICE GROUP WITH PARAMS - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc3"
          - "svc4"
        comment: "service group unit test"
        state: "absent"

    - name: DELETE SERVICE GROUP AGAIN - NO CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        state: "absent"


- name: CLEANUP FORTIMANAGER SERVICES FOR UNIT TESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  tags: cleanup
  
  tasks:
    - name: CLEANUP SERVICE GROUPS - CHANGE
      fortimgr_service_group:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_group_name: "{{ item.name }}"
        state: "absent"
      with_items:
        - name: "svcgrp1"
        - name: "svcgrp2"
        - name: "provider_svcgrp1"

    - name: CLEANUP SERVICES - CHANGE
      fortimgr_service:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adom: "lab"
        service_name: "{{ item.name }}"
        state: "absent"
      with_items:
        - name: "svc1"
        - name: "svc2"
        - name: "svc3"
        - name: "svc4"
